<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Assimalign.Cohesion.Test.Hosting</AssemblyName>
    <RootNamespace>Assimalign.Cohesion.Test.Hosting</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

</Project>
