<Project Sdk="Assimalign.Cohesion.Sdk.Web">

  <PropertyGroup>
    <CohesionApplicationModel>enabled</CohesionApplicationModel>
    <CohesionApplication>appa</CohesionApplication>
    <CohesionResourceName>appa-web</CohesionResourceName>
  </PropertyGroup>

  <ItemGroup>
    <CohesionResourceReference Include="..\PlatformDatabase\PlatformDatabase.csproj" Endpoints="db" />
  </ItemGroup>

</Project>
