<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Content.Yaml</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Content" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Content.Text" />
	</ItemGroup>
</Project>
