<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.ApplicationModel.Gateway.InProcess</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.ApplicationModel" />
		<CohesionProjectReference Include="Assimalign.Cohesion.ApplicationModel.Gateway" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources" />
	</ItemGroup>
	<ItemGroup>
		<None
			Include="..\buildTransitive\Assimalign.Cohesion.ApplicationModel.Gateway.InProcess.props"
			Pack="true"
			PackagePath="buildTransitive\Assimalign.Cohesion.ApplicationModel.Gateway.InProcess.props" />
	</ItemGroup>
</Project>
