<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Assimalign.Cohesion.Connections.Quic.Tests</RootNamespace>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <CohesionPackageReference Include="coverlet.collector" />
        <CohesionPackageReference Include="Microsoft.NET.Test.Sdk" />
        <CohesionPackageReference Include="Shouldly" />
        <CohesionPackageReference Include="xunit" />
        <CohesionPackageReference Include="xunit.runner.visualstudio" />
        <CohesionProjectReference Include="Assimalign.Cohesion.Connections.Quic" />
    </ItemGroup>
</Project>
