<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<CohesionSharedSource Include="Assimalign.Cohesion.Database" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Connections" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Graph.Language" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Graph.Storage" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Graph.Catalog" />
		<InternalsVisibleTo Include="Assimalign.Cohesion.Database.Graph.Tests" />
	</ItemGroup>
</Project>
