<Project Sdk="Assimalign.Cohesion.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>InProcessNonComposable</RootNamespace>
    <CohesionApplicationModel>enabled</CohesionApplicationModel>
    <CohesionApplication>gateway-smoke</CohesionApplication>
    <CohesionResourceName>inprocess-noncomposable</CohesionResourceName>
    <CohesionResourceComposable>false</CohesionResourceComposable>
  </PropertyGroup>

  <ItemGroup>
    <CohesionPackageReference Include="NUlid" />
    <None Update="content\noncomposable.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
