<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Web.CookiePolicy.Tests</RootNamespace>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<CohesionPackageReference Include="Microsoft.NET.Test.Sdk" />
		<CohesionPackageReference Include="coverlet.collector" />
		<CohesionPackageReference Include="xunit" />
		<CohesionPackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Web.CookiePolicy" />
	</ItemGroup>
</Project>