<Project>
	<PropertyGroup>
		<_CohesionDatabaseModelTargetsLoaded>true</_CohesionDatabaseModelTargetsLoaded>
		<_CohesionDatabaseModelCompileTarget>_CohesionCompileKeyValuePairDatabaseSchema</_CohesionDatabaseModelCompileTarget>
	</PropertyGroup>

	<Target
		Name="_CohesionCompileKeyValuePairDatabaseSchema"
		Condition="'$(CohesionDatabaseProject)' == 'true'"
		Inputs="@(Compile);@(ReferencePath);$(_CohesionDatabaseTaskAssembly)"
		Outputs="$(_CohesionDatabaseSchemaStamp)">
		<CompileDatabaseSchemaTask
			SourceFiles="@(Compile)"
			ReferencePaths="@(ReferencePath)"
			DefineConstants="$(DefineConstants)"
			LanguageVersion="$(LangVersion)"
			AssemblyName="$(AssemblyName)"
			Model="KeyValuePair"
			ProjectDirectory="$(MSBuildProjectDirectory)"
			OutputDirectory="$(CohesionDatabaseSchemaOutputDirectory)" />
		<Touch Files="$(_CohesionDatabaseSchemaStamp)" AlwaysCreate="true" />
	</Target>
</Project>
