<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Hosting.Resources.Tests</RootNamespace>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="TestObjects\Assimalign.Cohesion.Hosting.Resources.TestResource\Program.cs" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources" />
	</ItemGroup>
</Project>
