<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Hosting.Resources.Tests</RootNamespace>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="TestObjects\Assimalign.Cohesion.Hosting.Resources.TestResource\**\*.cs" />
	</ItemGroup>
	<ItemGroup>
		<CohesionPackageReference Include="Microsoft.NET.Test.Sdk" />
		<CohesionPackageReference Include="Shouldly" />
		<CohesionPackageReference Include="System.Security.Cryptography.ProtectedData" />
		<CohesionPackageReference Include="xunit" />
		<CohesionPackageReference Include="xunit.runner.visualstudio" />
		<CohesionPackageReference Include="coverlet.collector" />
	</ItemGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Health" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources.TestResource" />
	</ItemGroup>
</Project>
