<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">

  <PropertyGroup>
    <RootNamespace>InProcessTransitiveGateway</RootNamespace>
    <CohesionApplicationName>gateway-smoke</CohesionApplicationName>
    <CohesionResourceName>inprocess-transitive-gateway</CohesionResourceName>
    <CohesionGateways>InProcess</CohesionGateways>
    <CohesionGatewayInProcess>true</CohesionGatewayInProcess>
  </PropertyGroup>

  <ItemGroup>
    <CohesionResourceReference Include="..\GatewaySmokeWeb\GatewaySmokeWeb.csproj" />
  </ItemGroup>

</Project>
