<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">
  <PropertyGroup>
    <CohesionApplicationName>gateway-smoke</CohesionApplicationName>
    <CohesionResourceName>typed-identity-gateway</CohesionResourceName>
    <CohesionGatewayAot>false</CohesionGatewayAot>
  </PropertyGroup>
  <ItemGroup>
    <CohesionResourceReference Include="..\TypedIdentityHub\TypedIdentityHub.csproj" />
  </ItemGroup>
</Project>
