<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>Preview</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <CohesionProjectReference Include="Assimalign.Cohesion.Database" />
    <CohesionProjectReference Include="Assimalign.Cohesion.Database.Types" />
  </ItemGroup>
</Project>
