<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <CohesionGenerateDatabaseMappers>true</CohesionGenerateDatabaseMappers>
  </PropertyGroup>
  <ItemGroup>
    <CohesionPackageReference Include="Microsoft.NET.Test.Sdk" />
    <CohesionPackageReference Include="coverlet.collector" />
    <CohesionPackageReference Include="xunit" />
    <CohesionPackageReference Include="xunit.runner.visualstudio" />
    <CohesionPackageReference Include="Shouldly" />
    <CohesionProjectReference Include="Assimalign.Cohesion.Database.Sql.Mapping" />
    <CohesionProjectReference Include="Assimalign.Cohesion.Database.Sql" />
    <CohesionProjectReference Include="Assimalign.Cohesion.Database.Sql.Schema" />
    <CohesionProjectReference Include="Assimalign.Cohesion.Connections.InMemory" />
    <CohesionAnalyzerReference Include="Assimalign.Cohesion.SourceGeneration.Database" />
    <CompilerVisibleProperty Include="CohesionGenerateDatabaseMappers" />
  </ItemGroup>
</Project>
