using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

using Assimalign.Cohesion.Sdk.Tasks.Internal;

namespace Assimalign.Cohesion.Sdk.Gateway.Tasks;

internal static class GatewaySourceWriter
{
    public static void Write(
        string outputPath,
        string applicationName,
        IReadOnlyList<GatewayManifest> manifests,
        IReadOnlyList<GatewayManifest> resources,
        IReadOnlyList<GatewayExternal> externals,
        IReadOnlyList<GatewayManifest> applications,
        IReadOnlyList<GatewayResourceKind> resourceKinds,
        IReadOnlyList<GatewayProvider> providers)
    {
        var source = new StringBuilder(32768);
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        if (resources.Any(manifest => manifest.InProcessBinding is not null))
        {
            source.AppendLine("using Assimalign.Cohesion.ApplicationModel.Gateway.InProcess;");
            source.AppendLine();
        }
        source.Append("[assembly: global::Assimalign.Cohesion.ApplicationModel.CohesionApplicationAttribute(")
            .Append(Literal(applicationName))
            .AppendLine(")]");
        source.AppendLine();
        WriteGateway(source, applicationName);
        WriteManifests(source, manifests);
        WriteExternals(source, externals);
        WriteApplications(source, applications);
        WriteReferences(source, applications);
        WriteResourceExtensions(source, resources, externals, resourceKinds);
        WriteProviderCatalog(source, providers);
        WriteGatewayExtensions(source, providers);
        WriteIfChanged(outputPath, source.ToString());
    }

    public static string Identifier(string value) => CohesionIdentifier.ToPascalCase(value);

    public static string FriendlyManifestName(GatewayManifest manifest)
    {
        string identity = manifest.ProjectName;
        if (string.IsNullOrWhiteSpace(identity))
        {
            identity = Path.GetFileNameWithoutExtension(manifest.ReferenceIdentity);
        }

        string[] segments = identity.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (segments.Length > 0 && string.Equals(segments[^1], "Manifest", StringComparison.OrdinalIgnoreCase))
        {
            segments = segments[..^1];
        }

        int applicationIndex = Array.FindIndex(
            segments,
            segment => string.Equals(Slug(segment), manifest.Application, StringComparison.OrdinalIgnoreCase));
        if (applicationIndex >= 0)
        {
            string application = Identifier(segments[applicationIndex]);
            string[] suffix = segments[(applicationIndex + 1)..];
            if (suffix.Length == 0)
            {
                return application;
            }

            string joinedSuffix = string.Concat(suffix.Select(Identifier));
            return joinedSuffix.StartsWith(application, StringComparison.OrdinalIgnoreCase)
                ? joinedSuffix
                : application + joinedSuffix;
        }

        return Identifier(manifest.Name);
    }

    private static void WriteGateway(StringBuilder source, string applicationName)
    {
        source.AppendLine("/// <summary>Creates the build-generated Cohesion application builder.</summary>");
        source.AppendLine("public static partial class Gateway");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>Creates a builder with the compiled application identity and invocation arguments.</summary>");
        source.AppendLine("    /// <param name=\"args\">The gateway command-line arguments.</param>");
        source.AppendLine("    /// <returns>The application builder.</returns>");
        source.AppendLine("    /// <exception cref=\"global::System.ArgumentNullException\"><paramref name=\"args\" /> is null.</exception>");
        source.AppendLine("    public static global::Assimalign.Cohesion.ApplicationModel.IApplicationBuilder CreateBuilder(string[] args)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(args);");
        source.Append("        return global::Assimalign.Cohesion.ApplicationModel.Application.CreateBuilder(")
            .Append("global::Assimalign.Cohesion.ApplicationModel.ApplicationName.Parse(")
            .Append(Literal(applicationName))
            .AppendLine("), args);");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void WriteManifests(StringBuilder source, IReadOnlyList<GatewayManifest> manifests)
    {
        source.AppendLine("/// <summary>Contains the resource manifests captured by the gateway build.</summary>");
        source.AppendLine("public static class Manifests");
        source.AppendLine("{");
        foreach (GatewayManifest manifest in manifests.OrderBy(value => value.MemberName, StringComparer.Ordinal))
        {
            source.Append("    /// <summary>Gets the manifest for ")
                .Append(Xml(manifest.Application))
                .Append('/')
                .Append(Xml(manifest.Name))
                .AppendLine(".</summary>");
            source.Append("    public static readonly global::Assimalign.Cohesion.ApplicationModel.ResourceManifest ")
                .Append(manifest.MemberName)
                .Append(" = global::Assimalign.Cohesion.ApplicationModel.ResourceManifest.Parse(")
                .Append(Literal(manifest.RawJson))
                .AppendLine(");");
            source.AppendLine();
        }
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void WriteExternals(StringBuilder source, IReadOnlyList<GatewayExternal> externals)
    {
        source.AppendLine("/// <summary>Contains resources whose ownership boundary differs from this gateway.</summary>");
        source.AppendLine("public static class Externals");
        source.AppendLine("{");
        foreach (GatewayExternal external in externals.OrderBy(value => value.MemberName, StringComparer.Ordinal))
        {
            source.Append("    /// <summary>Gets the external declaration for ")
                .Append(Xml(external.Application))
                .Append('/')
                .Append(Xml(external.Resource))
                .AppendLine(".</summary>");
            source.Append("    public static readonly global::Assimalign.Cohesion.ApplicationModel.ExternalResourceDeclaration ")
                .Append(external.MemberName)
                .AppendLine(" = new(");
            source.Append("        (global::Assimalign.Cohesion.ApplicationModel.ResourceName)")
                .Append(Literal(external.Resource)).AppendLine(",");
            source.Append("        global::Assimalign.Cohesion.ApplicationModel.ApplicationName.Parse(")
                .Append(Literal(external.Application)).AppendLine("),");
            source.Append("        new string[] { ")
                .Append(string.Join(", ", external.Endpoints.OrderBy(value => value, StringComparer.Ordinal).Select(Literal)))
                .AppendLine(" },");
            source.Append("        optional: ").Append(external.Optional ? "true" : "false");
            if (external.Manifest is not null)
            {
                source.AppendLine(",");
                source.Append("        manifest: Manifests.").Append(external.Manifest.MemberName).AppendLine(",");
                source.Append("        closure: new global::Assimalign.Cohesion.ApplicationModel.ResourceManifest[] { ")
                    .Append(string.Join(", ", external.Closure.Select(value => $"Manifests.{value.MemberName}")))
                    .Append(" }");
            }
            source.AppendLine(");");
            source.AppendLine();
        }
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void WriteApplications(StringBuilder source, IReadOnlyList<GatewayManifest> applications)
    {
        source.AppendLine("/// <summary>Contains referenced gateway applications resolved through their control planes.</summary>");
        source.AppendLine("public static class Applications");
        source.AppendLine("{");
        foreach (GatewayManifest application in applications.OrderBy(value => value.Application, StringComparer.Ordinal))
        {
            string member = Identifier(application.Application);
            string exportPath = Path.Combine(".cohesion", application.Application, "export.json");
            source.Append("    /// <summary>Gets the application declaration for ")
                .Append(Xml(application.Application)).AppendLine(".</summary>");
            source.Append("    public static readonly global::Assimalign.Cohesion.ApplicationModel.ApplicationDeclaration ")
                .Append(member).AppendLine(" = new(");
            source.Append("        global::Assimalign.Cohesion.ApplicationModel.ApplicationName.Parse(")
                .Append(Literal(application.Application)).AppendLine("),");
            source.AppendLine("        global::Assimalign.Cohesion.ApplicationModel.ApplicationModelResolvers.ControlPlane(");
            source.Append("            ").Append(Literal(application.AppHostPath)).AppendLine(",");
            source.Append("            ").Append(Literal(exportPath)).AppendLine("));");
            source.AppendLine();
        }
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void WriteReferences(StringBuilder source, IReadOnlyList<GatewayManifest> applications)
    {
        source.AppendLine("/// <summary>Contains endpoint names re-exported by referenced Composite gateways.</summary>");
        source.AppendLine("public static class References");
        source.AppendLine("{");
        foreach (GatewayManifest application in applications.OrderBy(value => value.Application, StringComparer.Ordinal))
        {
            source.Append("    /// <summary>Contains re-exported endpoints for ")
                .Append(Xml(application.Application)).AppendLine(".</summary>");
            source.Append("    public static class ").Append(Identifier(application.Application)).AppendLine();
            source.AppendLine("    {");
            foreach (GatewayManifestEndpoint endpoint in application.Endpoints.OrderBy(value => value.Name, StringComparer.Ordinal))
            {
                source.Append("        /// <summary>Gets the re-exported endpoint name ")
                    .Append(Xml(endpoint.Name)).AppendLine(".</summary>");
                source.Append("        public const string ").Append(Identifier(endpoint.Name)).Append(" = ")
                    .Append(Literal(endpoint.Name)).AppendLine(";");
            }
            source.AppendLine("    }");
            source.AppendLine();
        }
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void WriteResourceExtensions(
        StringBuilder source,
        IReadOnlyList<GatewayManifest> resources,
        IReadOnlyList<GatewayExternal> externals,
        IReadOnlyList<GatewayResourceKind> resourceKinds)
    {
        source.AppendLine("/// <summary>Build-generated resource composition verbs.</summary>");
        source.AppendLine("public static class CohesionGatewayResourceExtensions");
        source.AppendLine("{");
        source.AppendLine("    extension(global::Assimalign.Cohesion.ApplicationModel.IApplicationBuilder builder)");
        source.AppendLine("    {");
        foreach (GatewayManifest manifest in resources)
        {
            GatewayResourceKind? kind = resourceKinds.FirstOrDefault(
                candidate => string.Equals(candidate.ApplicationModel, manifest.ApplicationModel, StringComparison.OrdinalIgnoreCase));
            string optionsType = kind?.OptionsType ?? "global::Assimalign.Cohesion.ApplicationModel.ResourceOptions";
            string descriptorType = kind?.DescriptorType ?? "global::Assimalign.Cohesion.ApplicationModel.IApplicationResourceDescriptor";
            source.Append("        /// <summary>Adds ").Append(Xml(manifest.Application)).Append('/')
                .Append(Xml(manifest.Name)).AppendLine(" to the application model.</summary>");
            source.AppendLine("        /// <param name=\"configure\">Optional platform-neutral planning overrides.</param>");
            source.AppendLine("        /// <returns>The resource descriptor, for adding dependency edges and resource commands.</returns>");
            if (manifest.InProcessBinding is GatewayInProcessBinding binding)
            {
                source.AppendLine("        [global::System.Diagnostics.CodeAnalysis.DynamicDependency(");
                source.AppendLine("            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods |");
                source.AppendLine("            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods,");
                source.Append("            ").Append(Literal(binding.EntryPointType)).AppendLine(",");
                source.Append("            ").Append(Literal(binding.EntryAssemblyName)).AppendLine(")]");
                source.AppendLine("        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(");
                source.AppendLine("            \"Trimming\",");
                source.AppendLine("            \"IL2026\",");
                source.AppendLine("            Justification = \"The generated DynamicDependency roots the resource entry point used by the in-process binding.\")]");
            }
            source.Append("        public ").Append(descriptorType).Append(" Add")
                .Append(manifest.MemberName).Append("(global::System.Action<").Append(optionsType)
                .AppendLine(">? configure = null)");
            source.AppendLine("        {");
            source.Append("            var options = new ").Append(optionsType).AppendLine("();");
            source.AppendLine("            configure?.Invoke(options);");
            if (kind is null || string.IsNullOrWhiteSpace(kind.AddMethod))
            {
                source.Append("            var descriptor = builder.AddResource(Manifests.").Append(manifest.MemberName)
                    .Append(", options)");
            }
            else
            {
                source.Append("            var descriptor = ").Append(kind.AddMethod).Append("(builder, Manifests.")
                    .Append(manifest.MemberName).Append(", options)");
            }
            source.AppendLine(";");
            WriteInProcessBinding(source, manifest.InProcessBinding);
            source.AppendLine("            return descriptor;");
            source.AppendLine("        }");
            source.AppendLine();
        }

        source.AppendLine("        /// <summary>Adds every same-application resource and embeds every boundary external.</summary>");
        source.AppendLine("        /// <returns>The builder, for chaining.</returns>");
        source.AppendLine("        public global::Assimalign.Cohesion.ApplicationModel.IApplicationBuilder AddAllResources()");
        source.AppendLine("        {");
        foreach (GatewayManifest manifest in resources)
        {
            source.Append("            builder.Add").Append(manifest.MemberName).AppendLine("();");
        }
        foreach (GatewayExternal external in externals.OrderBy(value => value.MemberName, StringComparer.Ordinal))
        {
            source.Append("            builder.AddExternal(Externals.").Append(external.MemberName).AppendLine(");");
        }
        source.AppendLine("            return builder;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void WriteInProcessBinding(
        StringBuilder source,
        GatewayInProcessBinding? binding)
    {
        if (binding is null)
        {
            return;
        }

        source.AppendLine();
        source.Append("            descriptor.InProcess(typeof(global::")
            .Append(binding.RootNamespace)
            .Append('.')
            .Append(EntryAnchorType(binding.EntryAssemblyName))
            .AppendLine(").Assembly,");
        source.AppendLine("                    global::System.IO.Path.Combine(");
        source.AppendLine("                        global::System.AppContext.BaseDirectory,");
        source.AppendLine("                        \"cohesion\",");
        source.AppendLine("                        \"resources\",");
        source.Append("                        ").Append(Literal(binding.ResourceName)).AppendLine("));");
    }

    private static void WriteProviderCatalog(StringBuilder source, IReadOnlyList<GatewayProvider> providers)
    {
        source.AppendLine("/// <summary>Configures only the gateway provider selected for this invocation.</summary>");
        source.AppendLine("public sealed class CohesionGatewayProviders");
        source.AppendLine("{");
        source.AppendLine("    private readonly string selected;");
        source.AppendLine("    private readonly string[] args;");
        source.AppendLine("    private readonly global::Assimalign.Cohesion.ApplicationModel.GatewayRunMode runMode;");
        source.AppendLine("    private global::Assimalign.Cohesion.ApplicationModel.IApplicationGateway? gateway;");
        source.AppendLine();
        source.AppendLine("    internal CohesionGatewayProviders(");
        source.AppendLine("        string selected,");
        source.AppendLine("        string[] args,");
        source.AppendLine("        global::Assimalign.Cohesion.ApplicationModel.GatewayRunMode runMode)");
        source.AppendLine("    {");
        source.AppendLine("        this.selected = selected;");
        source.AppendLine("        this.args = args;");
        source.AppendLine("        this.runMode = runMode;");
        source.AppendLine("    }");
        source.AppendLine();
        foreach (GatewayProvider provider in providers)
        {
            source.Append("    /// <summary>Configures the ").Append(Xml(provider.Name)).AppendLine(" gateway when selected.</summary>");
            source.AppendLine("    /// <param name=\"configure\">The provider-specific options callback.</param>");
            source.Append("    public void ").Append(provider.MemberName).Append("(global::System.Action<")
                .Append(provider.OptionsType).AppendLine(">? configure = null)");
            source.AppendLine("    {");
            source.Append("        if (!global::System.String.Equals(selected, ").Append(Literal(provider.Name))
                .AppendLine(", global::System.StringComparison.OrdinalIgnoreCase))");
            source.AppendLine("        {");
            source.AppendLine("            return;");
            source.AppendLine("        }");
            source.AppendLine();
            source.Append("        var options = new ").Append(provider.OptionsType).AppendLine("();");
            source.AppendLine("        configure?.Invoke(options);");
            source.AppendLine("        global::Assimalign.Cohesion.ApplicationModel.Gateway.ApplicationGatewayCommandLine.Apply(options, args);");
            WriteProviderCommandLine(source, provider, "        ");
            source.AppendLine("        global::Assimalign.Cohesion.ApplicationModel.Gateway.ControlPlane.GatewayControlPlane.Configure(options, runMode);");
            source.Append("        gateway = new ").Append(provider.GatewayType).AppendLine("(options);");
            source.AppendLine("    }");
            source.AppendLine();
        }
        source.AppendLine("    internal global::Assimalign.Cohesion.ApplicationModel.IApplicationGateway CreateSelected()");
        source.AppendLine("    {");
        source.AppendLine("        if (gateway is not null)");
        source.AppendLine("        {");
        source.AppendLine("            return gateway;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        return selected.ToLowerInvariant() switch");
        source.AppendLine("        {");
        foreach (GatewayProvider provider in providers)
        {
            source.Append("            ").Append(Literal(provider.Name.ToLowerInvariant())).Append(" => Create")
                .Append(provider.MemberName).AppendLine("(),");
        }
        source.AppendLine("            _ => throw UnknownGateway(selected)");
        source.AppendLine("        };");
        source.AppendLine("    }");
        source.AppendLine();
        foreach (GatewayProvider provider in providers)
        {
            source.Append("    private global::Assimalign.Cohesion.ApplicationModel.IApplicationGateway Create")
                .Append(provider.MemberName).AppendLine("()");
            source.AppendLine("    {");
            source.Append("        var options = new ").Append(provider.OptionsType).AppendLine("();");
            source.AppendLine("        global::Assimalign.Cohesion.ApplicationModel.Gateway.ApplicationGatewayCommandLine.Apply(options, args);");
            WriteProviderCommandLine(source, provider, "        ");
            source.AppendLine("        global::Assimalign.Cohesion.ApplicationModel.Gateway.ControlPlane.GatewayControlPlane.Configure(options, runMode);");
            source.Append("        return new ").Append(provider.GatewayType).AppendLine("(options);");
            source.AppendLine("    }");
            source.AppendLine();
        }
        WriteUnknownGateway(source, providers, 4);
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void WriteProviderCommandLine(
        StringBuilder source,
        GatewayProvider provider,
        string indent)
    {
        if (provider.CommandLineApplyMethod is null)
        {
            return;
        }

        source.Append(indent)
            .Append(provider.CommandLineApplyMethod)
            .AppendLine("(options, args);");
    }

    private static void WriteGatewayExtensions(StringBuilder source, IReadOnlyList<GatewayProvider> providers)
    {
        source.AppendLine("/// <summary>Build-generated gateway-provider selection verbs.</summary>");
        source.AppendLine("public static class CohesionGatewaySelectionExtensions");
        source.AppendLine("{");
        source.AppendLine("    extension(global::Assimalign.Cohesion.ApplicationModel.IApplicationBuilder builder)");
        source.AppendLine("    {");
        source.AppendLine("        /// <summary>Selects the requested contributed gateway provider.</summary>");
        source.AppendLine("        /// <param name=\"args\">The original gateway command-line arguments.</param>");
        source.AppendLine("        /// <returns>The builder, for chaining.</returns>");
        source.AppendLine("        public global::Assimalign.Cohesion.ApplicationModel.IApplicationBuilder UseGateway(string[] args)");
        source.AppendLine("        {");
        source.AppendLine("            string selected = ResolveGateway(builder, args);");
        source.AppendLine("            var gateways = new CohesionGatewayProviders(selected, args, builder.RunMode);");
        source.AppendLine("            return builder.UseGateway(gateways.CreateSelected());");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        /// <summary>Selects and optionally configures the requested contributed gateway provider.</summary>");
        source.AppendLine("        /// <param name=\"args\">The original gateway command-line arguments.</param>");
        source.AppendLine("        /// <param name=\"configure\">Provider-specific configuration; only the selected provider callback executes.</param>");
        source.AppendLine("        /// <returns>The builder, for chaining.</returns>");
        source.AppendLine("        public global::Assimalign.Cohesion.ApplicationModel.IApplicationBuilder UseGateway(");
        source.AppendLine("            string[] args,");
        source.AppendLine("            global::System.Action<CohesionGatewayProviders> configure)");
        source.AppendLine("        {");
        source.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(configure);");
        source.AppendLine("            string selected = ResolveGateway(builder, args);");
        source.AppendLine("            var gateways = new CohesionGatewayProviders(selected, args, builder.RunMode);");
        source.AppendLine("            configure(gateways);");
        source.AppendLine("            return builder.UseGateway(gateways.CreateSelected());");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static string ResolveGateway(");
        source.AppendLine("        global::Assimalign.Cohesion.ApplicationModel.IApplicationBuilder builder,");
        source.AppendLine("        string[] args)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(builder);");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(args);");
        source.AppendLine("        string? selected = builder.RequestedGateway?.ToString();");
        source.AppendLine("        if (global::System.String.IsNullOrWhiteSpace(selected))");
        source.AppendLine("        {");
        source.AppendLine("            selected = global::System.Environment.GetEnvironmentVariable(\"COHESION_GATEWAY\");");
        source.AppendLine("        }");
        source.AppendLine("        if (global::System.String.IsNullOrWhiteSpace(selected) && builder.Environment.IsLocal)");
        source.AppendLine("        {");
        source.AppendLine("            selected = \"local\";");
        source.AppendLine("        }");
        source.AppendLine("        return global::System.String.IsNullOrWhiteSpace(selected)");
        source.AppendLine("            ? throw new global::System.InvalidOperationException(");
        source.AppendLine("                \"No Cohesion gateway was selected. Pass --gateway, set COHESION_GATEWAY, or use Local for the local default.\")");
        source.AppendLine("            : selected;");
        source.AppendLine("    }");
        source.AppendLine();
        WriteUnknownGateway(source, providers, 4);
        source.AppendLine("}");
    }

    private static void WriteUnknownGateway(
        StringBuilder source,
        IReadOnlyList<GatewayProvider> providers,
        int spaces)
    {
        string indent = new(' ', spaces);
        string expected = string.Join(", ", providers.Select(provider => provider.Name).OrderBy(value => value, StringComparer.Ordinal));
        source.Append(indent).AppendLine("private static global::System.Exception UnknownGateway(string selected)");
        source.Append(indent).AppendLine("{");
        source.Append(indent).Append("    return new global::System.InvalidOperationException($\"Unknown Cohesion gateway '{selected}'. Expected ")
            .Append(EscapeInterpolated(expected)).AppendLine(".\");");
        source.Append(indent).AppendLine("}");
    }

    private static string Slug(string value)
    {
        var result = new StringBuilder(value.Length);
        foreach (char character in value)
        {
            if (char.IsAsciiLetterOrDigit(character))
            {
                result.Append(char.ToLowerInvariant(character));
            }
        }
        return result.ToString();
    }

    private static string Literal(string value)
    {
        return "\"" + value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal) + "\"";
    }

    private static string EntryAnchorType(string assemblyName) =>
        "CohesionResourceEntry" + Convert.ToHexString(Encoding.UTF8.GetBytes(assemblyName));

    private static string EscapeInterpolated(string value)
    {
        return value.Replace("{", "{{", StringComparison.Ordinal).Replace("}", "}}", StringComparison.Ordinal);
    }

    private static string Xml(string value)
    {
        return value.Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);
    }

    private static void WriteIfChanged(string path, string content)
    {
        string fullPath = Path.GetFullPath(path);
        Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
        if (File.Exists(fullPath) && string.Equals(File.ReadAllText(fullPath), content, StringComparison.Ordinal))
        {
            return;
        }

        string temporaryPath = fullPath + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try
        {
            File.WriteAllText(temporaryPath, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            File.Move(temporaryPath, fullPath, overwrite: true);
        }
        finally
        {
            if (File.Exists(temporaryPath))
            {
                File.Delete(temporaryPath);
            }
        }
    }
}
