<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Database.Sql.Language</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Language" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Types" />
	</ItemGroup>
</Project>
