<Project Sdk="Assimalign.Cohesion.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>StronglyTypedSettingsOptIn</RootNamespace>
    <CohesionAppSettingsClass>CatalogSettings</CohesionAppSettingsClass>
  </PropertyGroup>

</Project>
