<Project Sdk="Assimalign.Cohesion.Sdk">

  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>StronglyTypedSettingsOptIn</RootNamespace>
    <CohesionAppSettingsClass>CatalogSettings</CohesionAppSettingsClass>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Assimalign.Cohesion.App" />
  </ItemGroup>

</Project>
