<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.IoTHub" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Health" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Telemetry" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Web" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Web.Hosting" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Web.Hosting.Resources" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Http" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Http.Connections" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Connections.Tcp" />
	</ItemGroup>
</Project>
