<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageId>Assimalign.Cohesion.Sdk.Gateway</PackageId>
		<OutDir>$(CohesionOutputPathForSdk)\$(NETCoreSdkVersion)\sdks\$(PackageId)\Tasks</OutDir>
		<IsAotCompatible>true</IsAotCompatible>
		<EnablePreviewFeatures>false</EnablePreviewFeatures>
	</PropertyGroup>
	<ItemGroup>
		<CohesionPackageReference Include="Microsoft.Build" ExcludeAssets="runtime" />
		<CohesionPackageReference Include="Microsoft.Build.Framework" ExcludeAssets="runtime" />
		<CohesionPackageReference Include="Microsoft.Build.Utilities.Core" ExcludeAssets="runtime" />
	</ItemGroup>
</Project>
