<Project Sdk="Assimalign.Cohesion.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <IsAotCompatible>true</IsAotCompatible>
    <RootNamespace>InvalidOutputType</RootNamespace>
    <CohesionApplicationModel>enabled</CohesionApplicationModel>
    <CohesionApplication>inventory</CohesionApplication>
    <CohesionResourceName>inventory-library</CohesionResourceName>
    <CohesionResourceKind>Web</CohesionResourceKind>
    <CohesionControlPlaneEndpoint>http</CohesionControlPlaneEndpoint>
    <CohesionControlPlanePath>/cohesion/v1</CohesionControlPlanePath>
  </PropertyGroup>

  <ItemGroup>
    <CohesionEndpoint Include="http" Scheme="http" ContainerPort="8080" />
  </ItemGroup>

</Project>
