<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.OpenTelemetry.Tests</RootNamespace>
	</PropertyGroup>
	<PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
	<ItemGroup>
		<CohesionPackageReference Include="Microsoft.NET.Test.Sdk" />
		<CohesionPackageReference Include="xunit" />
		<CohesionPackageReference Include="xunit.runner.visualstudio" />
		<CohesionPackageReference Include="Shouldly" />
		<CohesionProjectReference Include="Assimalign.Cohesion.OpenTelemetry" />
	</ItemGroup>
</Project>
