<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.ConfigurationStore" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Health" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Telemetry" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.IdentityModel.Token.JsonWebToken" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Web.Hosting" />
	</ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Assimalign.Cohesion.ConfigurationStore.Hosting.Tests" />
  </ItemGroup>
</Project>
