<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Assimalign.Cohesion.Amqp.Connections</RootNamespace>
        <ImplicitUsings>disable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <CohesionProjectReference Include="Assimalign.Cohesion.Core" />
        <CohesionProjectReference Include="Assimalign.Cohesion.Connections" />
    </ItemGroup>
</Project>
