<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.IdentityHub.ApplicationModel.Tests</RootNamespace>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<CohesionPackageReference Include="Microsoft.NET.Test.Sdk" />
		<CohesionPackageReference Include="coverlet.collector" />
		<CohesionPackageReference Include="xunit" />
		<CohesionPackageReference Include="xunit.runner.visualstudio" />
		<CohesionPackageReference Include="Shouldly" />
		<CohesionProjectReference Include="Assimalign.Cohesion.IdentityHub.ApplicationModel" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Fixtures\plans\*.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
</Project>
