<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.ApplicationModel" />
		<CohesionProjectReference Include="Assimalign.Cohesion.ApplicationModel.Gateway" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Connections.Tcp" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Core" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Http" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Http.Connections" />
		<CohesionProjectReference Include="Assimalign.Cohesion.IdentityModel" />
		<CohesionProjectReference Include="Assimalign.Cohesion.IdentityModel.Token.JsonWebToken" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Web.Routing" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="Assimalign.Cohesion.ApplicationModel.Gateway.ControlPlane.Tests" />
	</ItemGroup>
	<ItemGroup>
		<None
			Include="..\buildTransitive\Assimalign.Cohesion.ApplicationModel.Gateway.ControlPlane.props"
			Pack="true"
			PackagePath="buildTransitive\Assimalign.Cohesion.ApplicationModel.Gateway.ControlPlane.props" />
	</ItemGroup>
</Project>
