
inputs:
    kind:
        description: "Either 'frameworks' or libraries'"
        type: string
        required: true

    container:
        description: "A required parameter"
        required: true

    project:
        description: "An optional parameter"
        required: true

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v2
          name: "Checkout: ${{ inputs.project }}"

        - name: .NET Installation
          uses: actions/setup-dotnet@v3
          with:
              dotnet-version: |
                  10.x
        - name: ".NET Restore: MSBuild Project"
          run: dotnet restore './build/Tasks'

        - name: ".NET Build:  MSBuild Project"
          run: dotnet build --configuration Release --no-restore
          working-directory: "./build/Tasks"

        - name: ".NET Restore: ${{ inputs.project  }}"
          run: dotnet restore './${{ inputs.kind }}/${{ inputs.container }}/${{ inputs.project }}'

        - name: ".NET Build: ${{ matrix.projects }}"
          run: dotnet build --configuration Release --no-restore
          working-directory: "./${{ inputs.kind }}/${{ inputs.container }}/${{ inputs.project }}"

        - name: ".NET Unit Tests: ${{ matrix.projects }}"
          if: hashFiles(format('./{0}/{1}/{2}/tests/{3}.Tests.csproj',  inputs.kind, inputs.container, inputs.project, inputs.project)) != ''
          run: dotnet test --configuration Release --no-restore
          working-directory: "./${{ inputs.kind }}/${{ inputs.container }}/${{ inputs.project }}/tests"
