//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assimalign.Cohesion.ObjectValidation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager _resourceMan;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assimalign.Cohesion.ObjectValidation.Properties.Resources", typeof(Resources).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        internal static string DefaultValidationErrorCode {
            get {
                return ResourceManager.GetString("DefaultValidationErrorCode", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; is outside the bounds of &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageBetweenOrEqualToRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageBetweenOrEqualToRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; is outside the bounds of &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageBetweenRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageBetweenRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must be in the format of an email address..
        /// </summary>
        internal static string DefaultValidationMessageEmailAddressRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageEmailAddressRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; was not empty..
        /// </summary>
        internal static string DefaultValidationMessageEmptyRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageEmptyRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must end with &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageEndWithRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageEndWithRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must equal &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageEqualToRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageEqualToRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must be greater than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageGreaterThanOrEqualToRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageGreaterThanOrEqualToRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must be greater than &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageGreaterThanRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageGreaterThanRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; is not within the required length of &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageLengthBetweenRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageLengthBetweenRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; requires an exact length of &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageLengthRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageLengthRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must be less than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageLessThanOrEqualToRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageLessThanOrEqualToRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must be less than &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageLessThanRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageLessThanRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must match this pattern &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageMatchesRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageMatchesRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; requires a maximum length of &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageMaxLengthRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageMaxLengthRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; requires a minimum length of &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageMinLengthRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageMinLengthRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must contain &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageMustContains {
            get {
                return ResourceManager.GetString("DefaultValidationMessageMustContains", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must not contain &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageMustNotContains {
            get {
                return ResourceManager.GetString("DefaultValidationMessageMustNotContains", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; was empty..
        /// </summary>
        internal static string DefaultValidationMessageNotEmptyRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageNotEmptyRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must not end with &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageNotEndWithRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageNotEndWithRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must not equal &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageNotEqualToRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageNotEqualToRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must not be null..
        /// </summary>
        internal static string DefaultValidationMessageNotNullRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageNotNullRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must not start with &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageNotStartWithRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageNotStartWithRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must be null..
        /// </summary>
        internal static string DefaultValidationMessageNullRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageNullRule", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following expression: &apos;{0}&apos; must start with &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultValidationMessageStartWithRule {
            get {
                return ResourceManager.GetString("DefaultValidationMessageStartWithRule", _resourceCulture);
            }
        }
    }
}
