<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <IsAotCompatible>true</IsAotCompatible>
    <CohesionApplicationName>root</CohesionApplicationName>
    <CohesionResourceName>root-gateway</CohesionResourceName>
    <CohesionGateways>Local</CohesionGateways>
    <CohesionIsApplicationSet>true</CohesionIsApplicationSet>
  </PropertyGroup>

  <ItemGroup>
    <CohesionResourceReference Include="..\AppAGateway\AppAGateway.csproj" />
  </ItemGroup>

</Project>
