<Project>
	<!-- Reserved extension point used by cohesion-platforms container gathering. -->
	<Import Project="Sdk.Resource.targets" />

	<PropertyGroup>
		<CohesionBuildResourceContainersDependsOn>$(CohesionBuildResourceContainersDependsOn)</CohesionBuildResourceContainersDependsOn>
	</PropertyGroup>
</Project>
