<Project>
	<UsingTask
		TaskName="Assimalign.Cohesion.Sdk.Tasks.CohesionCreateResourceManifest"
		AssemblyFile="..\Tasks\Assimalign.Cohesion.Sdk.Tasks.dll"
		Runtime="NET" />

	<PropertyGroup>
		<CohesionApplicationModel Condition="'$(CohesionApplicationModel)' == ''">disabled</CohesionApplicationModel>
		<CohesionApplication Condition="'$(CohesionApplication)' == '' and '$(CohesionApplicationName)' != ''">$(CohesionApplicationName)</CohesionApplication>
		<CohesionApplicationName Condition="'$(CohesionApplicationName)' == '' and '$(CohesionApplication)' != ''">$(CohesionApplication)</CohesionApplicationName>
		<CohesionResourceComposable Condition="'$(CohesionResourceComposable)' == ''">true</CohesionResourceComposable>
		<CohesionReplicas Condition="'$(CohesionReplicas)' == ''">1</CohesionReplicas>
		<CohesionStopGraceSeconds Condition="'$(CohesionStopGraceSeconds)' == ''">30</CohesionStopGraceSeconds>
		<CohesionRestartPolicy Condition="'$(CohesionRestartPolicy)' == ''">OnFailure</CohesionRestartPolicy>
	</PropertyGroup>

	<ItemDefinitionGroup>
		<CohesionEndpoint>
			<Scheme></Scheme>
			<ContainerPort></ContainerPort>
			<DevPort></DevPort>
			<Public>false</Public>
			<Certificate></Certificate>
			<Protocol>tcp</Protocol>
		</CohesionEndpoint>
		<CohesionProbe>
			<Endpoint></Endpoint>
			<Http></Http>
			<Tcp></Tcp>
			<Exec></Exec>
			<Grpc></Grpc>
			<None></None>
		</CohesionProbe>
		<CohesionMount>
			<Kind></Kind>
			<ContainerPath></ContainerPath>
			<Source></Source>
			<Size></Size>
		</CohesionMount>
		<CohesionSetting>
			<Default></Default>
			<Type>string</Type>
		</CohesionSetting>
		<CohesionResourceReference>
			<Version></Version>
			<Optional>false</Optional>
			<Endpoints></Endpoints>
		</CohesionResourceReference>
		<CohesionResourceProperty>
			<Value></Value>
		</CohesionResourceProperty>
	</ItemDefinitionGroup>
</Project>
