<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">
  <PropertyGroup>
    <RootNamespace>LogSpaceGateway</RootNamespace>
    <CohesionApplicationName>gateway-smoke</CohesionApplicationName>
    <CohesionResourceName>typed-logs-gateway</CohesionResourceName>
    <CohesionGatewayAot>false</CohesionGatewayAot>
  </PropertyGroup>
  <ItemGroup>
    <CohesionResourceReference Include="..\TypedLogSpace\TypedLogSpace.csproj" />
  </ItemGroup>
</Project>
