<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Database" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Documents.Language" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Documents.Storage" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Documents.Catalog" />
		<InternalsVisibleTo Include="Assimalign.Cohesion.Database.Documents.Tests" />
	</ItemGroup>
</Project>
