<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">
  <PropertyGroup>
    <RootNamespace>RezolvrGateway</RootNamespace>
    <CohesionApplicationName>gateway-smoke</CohesionApplicationName>
    <CohesionResourceName>typed-rezolvr-gateway</CohesionResourceName>
    <CohesionGatewayAot>false</CohesionGatewayAot>
  </PropertyGroup>
  <ItemGroup>
    <CohesionResourceReference Include="..\TypedRezolvr\TypedRezolvr.csproj" />
  </ItemGroup>
</Project>
