<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<Compile Remove="Delegates\**" />
		<Compile Remove="Extensions\**" />
		<Compile Remove="Internal\ScheduleTaskScheduler.cs" />
		<Compile Remove="Internal\SoftSchedulerNotifyDebounce.cs" />
		<Compile Remove="ValueObjects\JobId.generated.cs" />
		<Compile Remove="ValueObjects\ScheduleId.generated.cs" />
		<EmbeddedResource Remove="Delegates\**" />
		<EmbeddedResource Remove="Extensions\**" />
		<None Remove="Delegates\**" />
		<None Remove="Extensions\**" />
	</ItemGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Core" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting" />
	</ItemGroup>
	<ItemGroup>
		<CohesionValueType
			Include="ValueTypes\JobId.cs"
			ObjectRuntimeType="Ulid"
			ObjectNamespace="Assimalign.Cohesion.Scheduler"
			ObjectAccessModifier="public"
			ObjectHasImplicitOperators="true" />
		<CohesionValueType
			Include="ValueTypes\ScheduleId.cs"
			ObjectRuntimeType="Ulid"
			ObjectNamespace="Assimalign.Cohesion.Scheduler"
			ObjectAccessModifier="public"
			ObjectHasImplicitOperators="true" />
	</ItemGroup>
</Project>
