<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">

  <PropertyGroup>
    <RootNamespace>AppAGateway</RootNamespace>
    <CohesionApplicationName>appa</CohesionApplicationName>
    <CohesionResourceName>appa-gateway</CohesionResourceName>
    <CohesionGateways>Local</CohesionGateways>
  </PropertyGroup>

  <ItemGroup>
    <CohesionResourceReference Include="..\AppAWeb\AppAWeb.csproj" />
  </ItemGroup>

</Project>
