<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Database.Sql.Replication</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Sql" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Replication" />
	</ItemGroup>
</Project>
