<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources" />
    <CohesionProjectReference Include="Assimalign.Cohesion.Web.Hosting" />
  </ItemGroup>
</Project>
