<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Database.KeyValuePair.Catalog</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Database" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Storage" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.KeyValuePair.Storage" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Types" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Indexing" />
	</ItemGroup>
</Project>
