<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">
  <PropertyGroup>
    <RootNamespace>ThirdPartyGateway</RootNamespace>
    <CohesionApplicationName>gateway-smoke</CohesionApplicationName>
    <CohesionResourceName>third-party-gateway</CohesionResourceName>
    <CohesionGatewayAot>false</CohesionGatewayAot>
  </PropertyGroup>
  <ItemGroup>
    <CohesionPackageReference Include="ThirdParty.ApplicationModel" Version="$(CohesionVersion)" />
    <CohesionResourceReference Include="..\ThirdPartyResource\ThirdPartyResource.csproj" />
  </ItemGroup>
</Project>
