<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Web.Testing.Tests</RootNamespace>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Web.Testing" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Web.Testing.TestHost" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Core" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Web" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Web.Hosting" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Web.Routing" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Http" />
		<CohesionPackageReference Include="coverlet.collector" />
		<CohesionPackageReference Include="Microsoft.NET.Test.Sdk" />
		<CohesionPackageReference Include="Shouldly" />
		<CohesionPackageReference Include="xunit" />
		<CohesionPackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>
</Project>
