<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<CohesionPackageReference Include="Microsoft.NET.Test.Sdk" />
		<CohesionPackageReference Include="coverlet.collector" />
		<CohesionPackageReference Include="xunit" />
		<CohesionPackageReference Include="xunit.runner.visualstudio" />
		<CohesionPackageReference Include="Shouldly" />
		<CohesionProjectReference Include="Assimalign.Cohesion.ApplicationModel" />
		<CohesionProjectReference Include="Assimalign.Cohesion.ApplicationModel.Gateway" />
		<CohesionProjectReference Include="Assimalign.Cohesion.ConfigurationStore.ApplicationModel" />
		<CohesionProjectReference Include="Assimalign.Cohesion.ConfigurationStore.Client" />
		<CohesionProjectReference Include="Assimalign.Cohesion.ConfigurationStore.Hosting" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources" />
		<CohesionProjectReference Include="Assimalign.Cohesion.IdentityModel" />
		<CohesionProjectReference Include="Assimalign.Cohesion.IdentityModel.Token" />
		<CohesionProjectReference Include="Assimalign.Cohesion.IdentityModel.Token.JsonWebToken" />
	</ItemGroup>
</Project>
