<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Assimalign.Cohesion.Database.Blob.StreamingFixture</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>Preview</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot Condition="'$(BlobFixtureNativeAot)' == 'true'">true</PublishAot>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <CohesionProjectReference Include="Assimalign.Cohesion.Database.Blob" />
  </ItemGroup>
</Project>
