<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Http</RootNamespace>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ImplicitUsings>disable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Core" />
	</ItemGroup>
</Project>
