<Project Sdk="Assimalign.Cohesion.Sdk.SecretStore">
  <PropertyGroup>
    <RootNamespace>CommandSecretStore</RootNamespace>
    <CohesionApplicationModel>enabled</CohesionApplicationModel>
    <CohesionApplication>gateway-smoke</CohesionApplication>
    <CohesionResourceName>command-secrets</CohesionResourceName>
  </PropertyGroup>
</Project>
