<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Web.ApplicationModel</RootNamespace>
		<CohesionApplicationModelGuard>true</CohesionApplicationModelGuard>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.ApplicationModel" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting" />
	</ItemGroup>
</Project>
