<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.ObjectPool</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Internal\ObjectPoolDisposable.cs" />
	</ItemGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Core" />
	</ItemGroup>
</Project>
