<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Database.Blob.Catalog</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Database" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Blob.Storage" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Storage" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Database.Transactions" />
	</ItemGroup>
</Project>
