<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Web.Hosting.Health</RootNamespace>
		<Description>Hosting health contributor adapters for Cohesion Web health checks.</Description>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Health" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Web.Health" />
	</ItemGroup>
</Project>
