<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Http.Forwarded.Tests</RootNamespace>
		<IsPackable>false</IsPackable>
		<ImplicitUsings>disable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Http.Forwarded" />
		<CohesionPackageReference Include="coverlet.collector" />
		<CohesionPackageReference Include="Shouldly" />
		<CohesionPackageReference Include="Microsoft.NET.Test.Sdk" />
		<CohesionPackageReference Include="xunit" />
		<CohesionPackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>
</Project>
