<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="HostBuilderTests.cs" />
	  <Compile Remove="TestObjects\Assimalign.Cohesion.Hosting.TestResource\**\*.cs" />
	</ItemGroup>
	<ItemGroup>
		<CohesionPackageReference Include="Microsoft.NET.Test.Sdk" />
		<CohesionPackageReference Include="Shouldly" />
		<CohesionPackageReference Include="System.Security.Cryptography.ProtectedData" />
		<CohesionPackageReference Include="xunit" />
		<CohesionPackageReference Include="xunit.runner.visualstudio" />
		<CohesionPackageReference Include="coverlet.collector" />
	</ItemGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.TestResource" />
	</ItemGroup>
</Project>
