on:
    workflow_call:
        kind:
            description: "Either 'frameworks' or libraries'"
            type: string
        container:
            description: "A required parameter"
            required: true
        project:
            description: "An optional parameter"
            required: false
# runs:
#     using: "composite"
#     steps:
#         - uses: actions/checkout@v2
#           name: "Checkout: ${{ matrix.projects }}"

#         - name: .NET Installation
#           uses: actions/setup-dotnet@v3
#           with:
#               dotnet-version: |
#                   10.x
#         - name: ".NET Restore: MSBuild Project"
#           run: dotnet restore './build/Tasks'

#         - name: ".NET Build:  MSBuild Project"
#           run: dotnet build --configuration Release --no-restore
#           working-directory: "./build/Tasks"

#         - name: ".NET Restore: ${{ matrix.projects }}"
#           run: dotnet restore './libraries/Core/${{ matrix.projects }}'

#         - name: ".NET Build: ${{ matrix.projects }}"
#           run: dotnet build --configuration Release --no-restore
#           working-directory: "./libraries/Core/${{ matrix.projects }}"

#         - name: ".NET Unit Tests: ${{ matrix.projects }}"
#           if: hashFiles(format('./libraries/Core/{0}/tests/{1}.Tests.csproj', matrix.projects, matrix.projects)) != ''
#           run: dotnet test --configuration Release --no-restore
#           working-directory: "./libraries/Core/${{ matrix.projects }}/tests"
