<#!
.SYNOPSIS
Regenerates the persisted collation tables from checksum-pinned Unicode 17.0 data.
.DESCRIPTION
Download CaseFolding.txt and UnicodeData.txt from https://www.unicode.org/Public/17.0.0/ucd/
into InputDirectory, then invoke this script. Never update these tables in place for an
existing collation identifier: a Unicode version change requires a new persisted identity.
!#>
param([Parameter(Mandatory = $true)][string] $InputDirectory)

$ErrorActionPreference = 'Stop'
$expectedHashes = @{
    'CaseFolding.txt' = 'FF8D8FEFBF123574205085D6714C36149EB946D717A0C585C27F0F4EF58C4183'
    'UnicodeData.txt' = '2E1EFC1DCB59C575EEDF5CCAE60F95229F706EE6D031835247D843C11D96470C'
}
foreach ($name in $expectedHashes.Keys) {
    if ((Get-FileHash (Join-Path $InputDirectory $name) -Algorithm SHA256).Hash -ne $expectedHashes[$name]) {
        throw "The Unicode 17.0 checksum for $name does not match."
    }
}

$caseMappings = [System.Collections.Generic.List[int]]::new()
foreach ($line in Get-Content (Join-Path $InputDirectory 'CaseFolding.txt')) {
    if ($line -match '^([0-9A-F]+); [CS]; ([0-9A-F]+);') {
        $caseMappings.Add([Convert]::ToInt32($Matches[1], 16))
        $caseMappings.Add([Convert]::ToInt32($Matches[2], 16))
    }
}

$decompositions = [System.Collections.Generic.List[int]]::new()
$marks = [System.Collections.Generic.List[int]]::new()
foreach ($line in Get-Content (Join-Path $InputDirectory 'UnicodeData.txt')) {
    $fields = $line.Split(';')
    $scalar = [Convert]::ToInt32($fields[0], 16)
    $isMark = $fields[2] -in 'Mn', 'Mc', 'Me'
    if ([int]$fields[3] -ne 0 -and -not $isMark) {
        throw 'Canonical ordering cannot be omitted if non-mark characters have combining classes.'
    }
    if ($isMark) {
        $marks.Add($scalar)
    }
    if ($fields[5] -and -not $fields[5].StartsWith('<')) {
        $components = $fields[5].Split(' ')
        if ($components.Count -gt 2) { throw 'Unexpected canonical decomposition length.' }
        $decompositions.Add($scalar)
        $decompositions.Add([Convert]::ToInt32($components[0], 16))
        $decompositions.Add($(if ($components.Count -eq 2) { [Convert]::ToInt32($components[1], 16) } else { 0 }))
    }
}

$markRanges = [System.Collections.Generic.List[int]]::new()
foreach ($scalar in $marks) {
    if ($markRanges.Count -ne 0 -and $scalar -eq $markRanges[$markRanges.Count - 1] + 1) {
        $markRanges[$markRanges.Count - 1] = $scalar
    } else {
        $markRanges.Add($scalar)
        $markRanges.Add($scalar)
    }
}

$output = [System.Text.StringBuilder]::new()
[void]$output.AppendLine('// <auto-generated />')
[void]$output.AppendLine('// Unicode 17.0.0, Unicode License v3: see docs/UNICODE_LICENSE.txt.')
[void]$output.AppendLine('// Reproduce with tools/Generate-CollationUnicodeData.ps1; persisted IDs must never change meaning.')
[void]$output.AppendLine('using System;')
[void]$output.AppendLine()
[void]$output.AppendLine('namespace Assimalign.Cohesion.Database.Types;')
[void]$output.AppendLine()
[void]$output.AppendLine('internal static partial class CollationUnicodeData')
[void]$output.AppendLine('{')
foreach ($table in @(
    @{ Name = 'CaseMappings'; Values = $caseMappings },
    @{ Name = 'CanonicalDecompositions'; Values = $decompositions },
    @{ Name = 'MarkRanges'; Values = $markRanges }
)) {
    [void]$output.AppendLine("    private static ReadOnlySpan<int> $($table.Name) =>")
    [void]$output.AppendLine('    [')
    $values = $table.Values
    for ($i = 0; $i -lt $values.Count; $i += 12) {
        $last = [Math]::Min($i + 11, $values.Count - 1)
        $row = ($values[$i..$last] | ForEach-Object { '0x{0:X}' -f $_ }) -join ', '
        [void]$output.AppendLine("        $row,")
    }
    [void]$output.AppendLine('    ];')
    [void]$output.AppendLine()
}
[void]$output.AppendLine('}')
$target = Join-Path $PSScriptRoot '../src/Internal/CollationUnicodeData.Generated.cs'
[System.IO.File]::WriteAllText($target, $output.ToString().Replace("`r`n", "`n"), [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated $($caseMappings.Count / 2) simple folds, $($decompositions.Count / 3) canonical decompositions, and $($markRanges.Count / 2) mark ranges."
