using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

using Assimalign.Cohesion.Sdk.ApplicationModel.Tasks.Internal;

namespace Assimalign.Cohesion.Sdk.ApplicationModel.Tasks;

internal static class ResourceSourceWriter
{
    public static void WriteResource(string path, string rootNamespace, ResourceManifestModel manifest)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {rootNamespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>Provides strongly typed access to this Cohesion resource's runtime inputs.</summary>");
        builder.AppendLine("public static partial class Resource");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("    internal static void RegisterEndpointCertificates()");
        builder.AppendLine("    {");
        builder.AppendLine("        global::Assimalign.Cohesion.Hosting.Resources.ResourceRuntime.RegisterEndpointCertificates(typeof(Resource).Assembly,");
        builder.AppendLine("            new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.OrdinalIgnoreCase)");
        builder.AppendLine("            {");
        foreach (ResourceEndpointModel endpoint in manifest.Endpoints.Where(endpoint => !string.IsNullOrEmpty(endpoint.Certificate)))
        {
            builder.AppendLine($"                [{Quote(endpoint.Name)}] = {Quote(endpoint.Certificate ?? string.Empty)},");
        }
        builder.AppendLine("            });");
        builder.AppendLine("    }");
        builder.AppendLine("    /// <summary>Gets the resource name.</summary>");
        builder.AppendLine($"    public const string Name = {Quote(manifest.Name)};");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Gets the containing application name.</summary>");
        builder.AppendLine($"    public const string Application = {Quote(manifest.Application)};");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Gets the resource kind.</summary>");
        builder.AppendLine($"    public const string Kind = {Quote(manifest.Kind)};");
        builder.AppendLine();
        WriteManifestDefaults(builder, manifest.Endpoints, manifest.Settings);
        WriteSettingValueType(builder);
        if (manifest.References.Count > 0)
        {
            WriteReferenceEndpointType(builder);
        }
        WriteEndpoints(builder, manifest.Endpoints);
        WriteMounts(builder, manifest.Mounts);
        WriteSettings(builder, manifest.Settings);
        WriteReferences(builder, manifest.References);
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("/// <summary>Provides a compiler-rooted assembly anchor for generated gateway bindings.</summary>");
        builder.Append("public static class ").AppendLine(EntryAnchorType(manifest.Artifact.Assembly));
        builder.AppendLine("{");
        builder.AppendLine("}");

        ResourceFileWriter.WriteIfChanged(
            path,
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetBytes(builder.ToString()));
    }

    public static void WriteControlPlane(
        string path,
        string rootNamespace,
        string controlPlaneType,
        ResourceManifestModel manifest)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");

        if (string.IsNullOrWhiteSpace(controlPlaneType))
        {
            ResourceFileWriter.WriteIfChanged(
                path,
                new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetBytes(builder.ToString()));
            return;
        }

        builder.AppendLine();
        builder.AppendLine($"namespace {rootNamespace};");
        builder.AppendLine();
        builder.AppendLine("internal static class __CohesionResourceControlPlaneRegistration");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("    internal static void Register()");
        builder.AppendLine("    {");
        builder.AppendLine("        global::Assimalign.Cohesion.Hosting.Resources.ResourceRuntime.RegisterEntry(typeof(Resource).Assembly);");
        builder.AppendLine("        global::Assimalign.Cohesion.Hosting.Resources.ResourceRuntime.RegisterControlPlane(");
        builder.AppendLine("            typeof(Resource).Assembly,");
        builder.AppendLine("            static () => CreateControlPlane(),");
        builder.AppendLine($"            {manifest.Lifecycle.StopGraceSeconds.ToString(CultureInfo.InvariantCulture)});");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static global::Assimalign.Cohesion.Hosting.Resources.IResourceControlPlane CreateControlPlane()");
        builder.AppendLine("    {");
        builder.AppendLine($"        global::Assimalign.Cohesion.Hosting.Resources.IResourceControlPlane controlPlane = global::{controlPlaneType}.Create();");
        builder.AppendLine("        global::Assimalign.Cohesion.Hosting.Resources.ResourceContext context = global::Assimalign.Cohesion.Hosting.Resources.ResourceRuntime.Current;");
        for (int index = 0; index < manifest.Endpoints.Count; index++)
        {
            ResourceEndpointModel endpoint = manifest.Endpoints[index];
            string devPort = endpoint.DevPort is int port
                ? port.ToString(CultureInfo.InvariantCulture)
                : "null";
            builder.AppendLine(
                $"        if (context.TryGetEndpoint({Quote(endpoint.Name)}, {Quote(endpoint.Scheme)}, {devPort}, out global::System.Uri? endpoint{index.ToString(CultureInfo.InvariantCulture)}))");
            builder.AppendLine("        {");
            builder.AppendLine(
                $"            controlPlane.ObserveEndpoint({Quote(endpoint.Name)}, endpoint{index.ToString(CultureInfo.InvariantCulture)});");
            builder.AppendLine("        }");
        }
        builder.AppendLine();
        builder.AppendLine("        return controlPlane;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        ResourceFileWriter.WriteIfChanged(
            path,
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetBytes(builder.ToString()));
    }

    public static string Identifier(string value) => CohesionIdentifier.ToPascalCase(value);

    private static string EntryAnchorType(string assemblyName) =>
        "CohesionResourceEntry" + Convert.ToHexString(Encoding.UTF8.GetBytes(assemblyName));

    private static void WriteManifestDefaults(
        StringBuilder builder,
        IReadOnlyList<ResourceEndpointModel> endpoints,
        IReadOnlyList<ResourceSettingModel> settings)
    {
        builder.AppendLine("    internal static readonly ResourceManifestDefaults Manifest = new(");
        builder.AppendLine("        new ResourceEndpointDefault[]");
        builder.AppendLine("        {");
        foreach (ResourceEndpointModel endpoint in endpoints)
        {
            string devPort = endpoint.DevPort is int port
                ? port.ToString(CultureInfo.InvariantCulture)
                : "null";
            builder.AppendLine(
                $"            new({Quote(endpoint.Name)}, {Quote(endpoint.Scheme)}, {endpoint.ContainerPort.ToString(CultureInfo.InvariantCulture)}, {devPort}),");
        }
        builder.AppendLine("        },");
        builder.AppendLine("        new ResourceSettingDefault[]");
        builder.AppendLine("        {");
        foreach (ResourceSettingModel setting in settings)
        {
            builder.AppendLine($"            new({Quote(setting.Key)}, {QuoteNullable(setting.Default)}),");
        }
        builder.AppendLine("        });");
        builder.AppendLine();
        builder.AppendLine("    internal sealed class ResourceManifestDefaults");
        builder.AppendLine("    {");
        builder.AppendLine("        internal ResourceManifestDefaults(ResourceEndpointDefault[] endpoints, ResourceSettingDefault[] settings)");
        builder.AppendLine("        {");
        builder.AppendLine("            Endpoints = endpoints;");
        builder.AppendLine("            Settings = settings;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        internal global::System.Collections.Generic.IReadOnlyList<ResourceEndpointDefault> Endpoints { get; }");
        builder.AppendLine();
        builder.AppendLine("        internal global::System.Collections.Generic.IReadOnlyList<ResourceSettingDefault> Settings { get; }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal readonly record struct ResourceEndpointDefault(string Name, string Scheme, int ContainerPort, int? DevPort);");
        builder.AppendLine();
        builder.AppendLine("    internal readonly record struct ResourceSettingDefault(string Key, string? Default);");
        builder.AppendLine();
    }

    private static void WriteSettingValueType(StringBuilder builder)
    {
        builder.AppendLine("    /// <summary>Represents one typed setting resolved from the current resource context.</summary>");
        builder.AppendLine("    /// <typeparam name=\"TDeclared\">The setting type declared by CohesionSetting metadata.</typeparam>");
        builder.AppendLine("    public readonly struct SettingValue<TDeclared>");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly string _key;");
        builder.AppendLine("        private readonly string? _fallback;");
        builder.AppendLine("        private readonly global::System.Func<string, TDeclared> _parser;");
        builder.AppendLine();
        builder.AppendLine("        internal SettingValue(string key, string? fallback, global::System.Func<string, TDeclared> parser)");
        builder.AppendLine("        {");
        builder.AppendLine("            _key = key;");
        builder.AppendLine("            _fallback = fallback;");
        builder.AppendLine("            _parser = parser;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Gets the configured value as its declared type.</summary>");
        builder.AppendLine("        /// <typeparam name=\"T\">The setting type declared in the project.</typeparam>");
        builder.AppendLine("        /// <returns>The configured or manifest-defaulted value.</returns>");
        builder.AppendLine("        /// <exception cref=\"global::System.InvalidOperationException\">Thrown when <typeparamref name=\"T\"/> does not match the declared type.</exception>");
        builder.AppendLine("        public T Get<T>()");
        builder.AppendLine("        {");
        builder.AppendLine("            if (typeof(T) != typeof(TDeclared))");
        builder.AppendLine("            {");
        builder.AppendLine("                throw new global::System.InvalidOperationException(");
        builder.AppendLine("                    $\"Cohesion setting '{_key}' is declared as '{typeof(TDeclared).FullName}', not '{typeof(T).FullName}'.\");");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            TDeclared value = _parser(global::Assimalign.Cohesion.Hosting.Resources.ResourceRuntime.Current.GetSetting(_key, _fallback));");
        builder.AppendLine("            return (T)(object)value!;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        internal static TEnum ParseEnum<TEnum>(string value)");
        builder.AppendLine("            where TEnum : struct, global::System.Enum");
        builder.AppendLine("        {");
        builder.AppendLine("            return global::System.Enum.Parse<TEnum>(value, ignoreCase: true);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void WriteReferenceEndpointType(StringBuilder builder)
    {
        builder.AppendLine("    /// <summary>Represents a dynamically resolved endpoint on a referenced resource.</summary>");
        builder.AppendLine("    public readonly struct ReferenceEndpoint");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly string _resource;");
        builder.AppendLine("        private readonly string _endpoint;");
        builder.AppendLine("        private readonly string _protocol;");
        builder.AppendLine();
        builder.AppendLine("        internal ReferenceEndpoint(string resource, string endpoint, string protocol)");
        builder.AppendLine("        {");
        builder.AppendLine("            _resource = resource;");
        builder.AppendLine("            _endpoint = endpoint;");
        builder.AppendLine("            _protocol = protocol;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Gets the currently observed endpoint URL.</summary>");
        builder.AppendLine("        /// <exception cref=\"global::System.InvalidOperationException\">Thrown when the endpoint is not currently resolved.</exception>");
        builder.AppendLine("        public global::System.Uri Url =>");
        builder.AppendLine("            global::Assimalign.Cohesion.Hosting.Resources.ResourceRuntime.Current.GetReference(_resource, _endpoint);");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Attempts to get the currently observed endpoint URL.</summary>");
        builder.AppendLine("        /// <param name=\"url\">The endpoint URL when this method returns <see langword=\"true\"/>.</param>");
        builder.AppendLine("        /// <returns><see langword=\"true\"/> when the endpoint is resolved; otherwise, <see langword=\"false\"/>.</returns>");
        builder.AppendLine("        public bool TryGetUrl([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::System.Uri? url)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (global::Assimalign.Cohesion.Hosting.Resources.ResourceRuntime.Current.TryGetReference(_resource, _endpoint, out global::System.Uri? address))");
        builder.AppendLine("            {");
        builder.AppendLine("                url = address;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            url = null;");
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Creates a connection factory for this endpoint's declared transport.</summary>");
        builder.AppendLine("        /// <returns>A connection factory for the endpoint transport.</returns>");
        builder.AppendLine("        /// <exception cref=\"global::System.NotSupportedException\">Thrown when the endpoint transport is not a stream connection.</exception>");
        builder.AppendLine("        public global::Assimalign.Cohesion.Connections.IConnectionFactory ConnectionFactory() =>");
        builder.AppendLine("            global::Assimalign.Cohesion.Hosting.Resources.ResourceRuntime.Current.GetConnectionFactory<global::Assimalign.Cohesion.Connections.IConnectionFactory>(_resource, _endpoint, _protocol);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void WriteEndpoints(StringBuilder builder, IReadOnlyList<ResourceEndpointModel> endpoints)
    {
        builder.AppendLine("    /// <summary>Provides this resource's declared endpoints.</summary>");
        builder.AppendLine("    public static class Endpoints");
        builder.AppendLine("    {");
        foreach (ResourceEndpointModel endpoint in endpoints)
        {
            string fallbackPort = endpoint.DevPort is int devPort
                ? devPort.ToString(CultureInfo.InvariantCulture)
                : "null";
            builder.AppendLine($"        /// <summary>Gets the {XmlText(endpoint.Name)} endpoint.</summary>");
            builder.AppendLine($"        public static global::System.Uri {Identifier(endpoint.Name)} =>");
            builder.AppendLine($"            global::Assimalign.Cohesion.Hosting.Resources.ResourceRuntime.Current.GetEndpoint({Quote(endpoint.Name)}, {Quote(endpoint.Scheme)}, {fallbackPort});");
            builder.AppendLine();
        }
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void WriteMounts(StringBuilder builder, IReadOnlyList<ResourceMountModel> mounts)
    {
        builder.AppendLine("    /// <summary>Provides this resource's materialized mounts.</summary>");
        builder.AppendLine("    public static class Mounts");
        builder.AppendLine("    {");
        foreach (ResourceMountModel mount in mounts)
        {
            builder.AppendLine($"        /// <summary>Gets the {XmlText(mount.Name)} mount.</summary>");
            builder.AppendLine($"        public static global::Assimalign.Cohesion.Hosting.Resources.ResourceMount {Identifier(mount.Name)} =>");
            builder.AppendLine($"            global::Assimalign.Cohesion.Hosting.Resources.ResourceRuntime.Current.GetMount({Quote(mount.Name)}, {Quote(mount.ContainerPath)});");
            builder.AppendLine();
        }
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void WriteSettings(StringBuilder builder, IReadOnlyList<ResourceSettingModel> settings)
    {
        builder.AppendLine("    /// <summary>Provides this resource's configured settings.</summary>");
        builder.AppendLine("    public static class Settings");
        builder.AppendLine("    {");
        foreach (ResourceSettingModel setting in settings)
        {
            string type = SettingType(setting.Type);
            builder.AppendLine($"        /// <summary>Gets the {XmlText(setting.Key)} setting.</summary>");
            builder.AppendLine($"        public static SettingValue<{type}> {Identifier(setting.Key)} =>");
            builder.AppendLine($"            new({Quote(setting.Key)}, {QuoteNullable(setting.Default)}, {SettingParser(type)});");
            builder.AppendLine();
        }
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void WriteReferences(StringBuilder builder, IReadOnlyList<ResourceReferenceModel> references)
    {
        builder.AppendLine("    /// <summary>Provides endpoints exposed by referenced resources.</summary>");
        builder.AppendLine("    public static class References");
        builder.AppendLine("    {");
        foreach (ResourceReferenceModel reference in references)
        {
            builder.AppendLine($"        /// <summary>Provides endpoints exposed by {XmlText(reference.Resource)}.</summary>");
            builder.AppendLine($"        public static class {Identifier(reference.Resource)}");
            builder.AppendLine("        {");
            foreach (ResourceEndpointModel endpoint in reference.Endpoints)
            {
                builder.AppendLine($"            /// <summary>Gets the {XmlText(endpoint.Name)} endpoint reference.</summary>");
                builder.AppendLine($"            public static ReferenceEndpoint {Identifier(endpoint.Name)} => new({Quote(reference.Resource)}, {Quote(endpoint.Name)}, {Quote(endpoint.Protocol)});");
                builder.AppendLine();
            }
            builder.AppendLine("        }");
            builder.AppendLine();
        }
        builder.AppendLine("    }");
    }

    private static string SettingType(string value)
    {
        return value.ToLowerInvariant() switch
        {
            "string" => "string",
            "int" or "int32" => "int",
            "bool" or "boolean" => "bool",
            "timespan" or "system.timespan" => "global::System.TimeSpan",
            "uri" or "system.uri" => "global::System.Uri",
            _ when value.StartsWith("global::", StringComparison.Ordinal) => value.Replace('+', '.'),
            _ when value.Contains('.', StringComparison.Ordinal) || value.Contains('+', StringComparison.Ordinal) =>
                $"global::{value.Replace('+', '.')}",
            _ => value
        };
    }

    private static string SettingParser(string type)
    {
        return type switch
        {
            "string" => "static value => value",
            "int" => "static value => int.Parse(value, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture)",
            "bool" => "static value => bool.Parse(value)",
            "global::System.TimeSpan" => "static value => global::System.TimeSpan.Parse(value, global::System.Globalization.CultureInfo.InvariantCulture)",
            "global::System.Uri" => "static value => new global::System.Uri(value, global::System.UriKind.Absolute)",
            _ => $"static value => SettingValue<{type}>.ParseEnum<{type}>(value)"
        };
    }

    private static string QuoteNullable(string? value)
    {
        return value is null ? "null" : Quote(value);
    }

    private static string Quote(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (char character in value)
        {
            switch (character)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                case '\u0085':
                    builder.Append("\\u0085");
                    break;
                case '\u2028':
                    builder.Append("\\u2028");
                    break;
                case '\u2029':
                    builder.Append("\\u2029");
                    break;
                default:
                    if (char.IsControl(character))
                    {
                        builder.Append("\\u");
                        builder.Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        builder.Append(character);
                    }
                    break;
            }
        }
        builder.Append('"');
        return builder.ToString();
    }

    private static string XmlText(string value)
    {
        return value
            .Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);
    }
}
