<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <CohesionProjectReference Include="Assimalign.Cohesion.Database" />
    <CohesionProjectReference Include="Assimalign.Cohesion.Database.Client" />
    <CohesionProjectReference Include="Assimalign.Cohesion.Database.Blob" />
    <CohesionProjectReference Include="Assimalign.Cohesion.Database.Protocol" />
    <CohesionProjectReference Include="Assimalign.Cohesion.Connections" />
  </ItemGroup>
</Project>
