<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		
		<RootNamespace>Assimalign.Cohesion</RootNamespace>
		<AssemblyName>Assimalign.Cohesion.App.IoTHub.Refs</AssemblyName>

		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateDependencyFile>false</GenerateDependencyFile>

		<PackageId>Assimalign.Cohesion.App.IoTHub.Ref</PackageId>
		<IsPackable>true</IsPackable>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<NoWarn>$(NoWarn);NU5128;NU5100;NU5131</NoWarn>

		<CohesionFrameworkName>Assimalign.Cohesion.App.IoTHub</CohesionFrameworkName>
		<CohesionFrameworkKind>Ref</CohesionFrameworkKind>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Assimalign.Cohesion.IoTHub.Runtime\src\Assimalign.Cohesion.IoTHub.Runtime.csproj"
			ReferenceOutputAssembly="false"
			SkipGetTargetFrameworkProperties="true"
			UndefineProperties="TargetFramework;RuntimeIdentifier" />
	</ItemGroup>

	<Import Project="$(CohesionRepositoryDirectory)libraries\App\Assimalign.Cohesion.App.props" />
	<Import Project="$(CohesionRepositoryDirectory)libraries\App\Assimalign.Cohesion.App.targets" />
</Project>