<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.IdentityHub.Models</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Core" />
		<CohesionProjectReference Include="Assimalign.Cohesion.IdentityModel" />
	</ItemGroup>
	<ItemGroup>
		<CohesionValueType
			Include="ValueObjects\Username.cs"
			ObjectRuntimeType="String"
			ObjectNamespace="Assimalign.Cohesion.IdentityHub.Models"
			ObjectAccessModifier="public"
			ObjectHasImplicitOperators="true" />
		<CohesionValueType
			Include="ValueObjects\Domain.cs"
			ObjectRuntimeType="String"
			ObjectNamespace="Assimalign.Cohesion.IdentityHub.Models"
			ObjectAccessModifier="public"
			ObjectHasImplicitOperators="true" />
		<CohesionValueType
			Include="ValueObjects\ObjectId.cs"
			ObjectRuntimeType="Ulid"
			ObjectNamespace="Assimalign.Cohesion.IdentityHub.Models"
			ObjectAccessModifier="public"
			ObjectHasImplicitOperators="true" />
		<CohesionValueType
			Include="ValueObjects\TenantId.cs"
			ObjectRuntimeType="Ulid"
			ObjectNamespace="Assimalign.Cohesion.IdentityHub.Models"
			ObjectAccessModifier="public"
			ObjectHasImplicitOperators="true" />
		<CohesionValueType
			Include="ValueObjects\UserId.cs"
			ObjectRuntimeType="Ulid"
			ObjectNamespace="Assimalign.Cohesion.IdentityHub.Models"
			ObjectAccessModifier="public"
			ObjectHasImplicitOperators="true" />
		<CohesionValueType
			Include="ValueObjects\GroupId.cs"
			ObjectRuntimeType="Ulid"
			ObjectNamespace="Assimalign.Cohesion.IdentityHub.Models"
			ObjectAccessModifier="public"
			ObjectHasImplicitOperators="true" />
		<CohesionValueType
			Include="ValueObjects\ApplicationId.cs"
			ObjectRuntimeType="Ulid"
			ObjectNamespace="Assimalign.Cohesion.IdentityHub.Models"
			ObjectAccessModifier="public"
			ObjectHasImplicitOperators="true" />
		<CohesionValueType
			Include="ValueObjects\RoleId.cs"
			ObjectRuntimeType="Ulid"
			ObjectNamespace="Assimalign.Cohesion.IdentityHub.Models"
			ObjectAccessModifier="public"
			ObjectHasImplicitOperators="true" />
		<CohesionValueType
			Include="ValueObjects\PermissionId.cs"
			ObjectRuntimeType="Ulid"
			ObjectNamespace="Assimalign.Cohesion.IdentityHub.Models"
			ObjectAccessModifier="public"
			ObjectHasImplicitOperators="true" />
	</ItemGroup>
</Project>
