<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.LogSpace.Hosting</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.LogSpace" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Health" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Telemetry" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.IdentityModel" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.IdentityModel.Token" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.IdentityModel.Token.JsonWebToken" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Http.RequestLimits" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Web" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Web.Hosting" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Web.Hosting.Resources" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Http" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Http.Connections" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Connections.Tcp" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Connections" />
		<CohesionPrivateProjectReference Include="Assimalign.Cohesion.Connections.Security" />
	</ItemGroup>
</Project>
