<Project Sdk="Assimalign.Cohesion.Sdk.Database">

  <PropertyGroup>
    <RootNamespace>GatewaySmokeDatabase</RootNamespace>
    <CohesionApplicationModel>enabled</CohesionApplicationModel>
    <CohesionApplication>gateway-smoke</CohesionApplication>
    <CohesionResourceName>gateway-smoke-database</CohesionResourceName>
  </PropertyGroup>

  <ItemGroup>
    <CohesionPackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    <None Update="content\database.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
