<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Web</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.Web" />
        <CohesionProjectReference Include="Assimalign.Cohesion.Http.Forms" />
	</ItemGroup>
</Project>