<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.Database.Storage</RootNamespace>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
		<CohesionProjectReference Include="Assimalign.Cohesion.FileSystem" />
		<CohesionProjectReference Include="Assimalign.Cohesion.FileSystem.Physical" />
	</ItemGroup>
</Project>
