<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">

  <PropertyGroup>
    <RootNamespace>DisabledGateway</RootNamespace>
    <CohesionApplicationName>disabled-test</CohesionApplicationName>
    <CohesionResourceName>disabled-test-gateway</CohesionResourceName>
    <CohesionGateways>Local</CohesionGateways>
  </PropertyGroup>

  <ItemGroup>
    <CohesionResourceReference Include="..\DisabledResource\DisabledResource.csproj" />
  </ItemGroup>

</Project>
