<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <CohesionPackageReference Include="coverlet.collector" />
    <CohesionPackageReference Include="Microsoft.NET.Test.Sdk" />
    <CohesionPackageReference Include="xunit" />
    <CohesionPackageReference Include="xunit.runner.visualstudio" />
    <CohesionPackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <CohesionProjectReference Include="Assimalign.Cohesion.ApplicationModel" />
    <CohesionProjectReference Include="Assimalign.Cohesion.ApplicationModel.Gateway" />
    <CohesionProjectReference Include="Assimalign.Cohesion.ApplicationModel.Gateway.TestHost" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="TestHost/**/*.cs" />
  </ItemGroup>

</Project>
