<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Assimalign.Cohesion.IdentityHub.Hosting.Tests</RootNamespace>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<CohesionPackageReference Include="Microsoft.NET.Test.Sdk" />
		<CohesionPackageReference Include="coverlet.collector" />
		<CohesionPackageReference Include="xunit" />
		<CohesionPackageReference Include="xunit.runner.visualstudio" />
		<CohesionPackageReference Include="Shouldly" />
		<CohesionProjectReference Include="Assimalign.Cohesion.IdentityHub.Hosting" />
		<CohesionProjectReference Include="Assimalign.Cohesion.Hosting.Resources" />
		<CohesionProjectReference Include="Assimalign.Cohesion.IdentityModel" />
		<CohesionProjectReference Include="Assimalign.Cohesion.IdentityModel.Token" />
		<CohesionProjectReference Include="Assimalign.Cohesion.IdentityModel.Token.JsonWebToken" />
	</ItemGroup>
</Project>
