name: Core

on:
  push:
    paths:
      - "**/Directory.Build.props" # When the Global Props File Changes
      - "libraries/Core/**"
      - ".github/workflows/core.yml" # When Pipeline File Changes
  # pull_request:
  #   paths:
  #     - "**/Directory.Build.props" # When the Global Props File Changes
  #     - "libraries/Core/**"
  #     - ".github/workflows/core.yml" # When Pipeline File Changes

jobs:
  build:
    name: "${{ matrix.projects }} [${{ matrix.os }}]"
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: [
            # 'Assimalign.Cohesion.Caching',
            'Assimalign.Cohesion.Configuration',
            'Assimalign.Cohesion.Configuration.CommandLine',
            'Assimalign.Cohesion.Configuration.EnvironmentVariables',
            'Assimalign.Cohesion.Configuration.FileSystem',
            # 'Assimalign.Cohesion.Configuration.Ini',
            'Assimalign.Cohesion.Configuration.Json',
            'Assimalign.Cohesion.Configuration.Xml',
            "Assimalign.Cohesion.Core",
            # 'Assimalign.Cohesion.DependencyInjection',
            "Assimalign.Cohesion.FileSystem",
            # 'Assimalign.Cohesion.FileSystem.Composite',
            'Assimalign.Cohesion.FileSystem.Globbing',
            'Assimalign.Cohesion.FileSystem.InMemory',
            'Assimalign.Cohesion.FileSystem.Physical',
            "Assimalign.Cohesion.Hosting",
            # 'Assimalign.Cohesion.Logging',
            # 'Assimalign.Cohesion.Logging.Console',
            'Assimalign.Cohesion.ObjectMapping',
            "Assimalign.Cohesion.ObjectPool",
            "Assimalign.Cohesion.ObjectValidation",
            "Assimalign.Cohesion.Transports",  
            # 'Assimalign.Cohesion.Security.Cryptography',
            'Assimalign.Cohesion.Resilience',
            # 'Assimalign.Cohesion.Resilience.CircuitBreaker',
            # 'Assimalign.Cohesion.Resilience.Fallback',
            # 'Assimalign.Cohesion.Resilience.Hedging',
            # 'Assimalign.Cohesion.Resilience.RateLimiting',
            'Assimalign.Cohesion.Resilience.Retry',
            'Assimalign.Cohesion.Resilience.Timeout',
          ]
    steps:
      - uses: actions/checkout@v2
        name: "Checkout: ${{ matrix.projects }}"

      - name: .NET Installation
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            10.x
      - name: ".NET Restore: MSBuild Project"
        run: dotnet restore './build/Tasks'
        
      - name: ".NET Build:  MSBuild Project"
        run: dotnet build --configuration Release --no-restore
        working-directory: "./build/Tasks"

      - name: ".NET Restore: ${{ matrix.projects }}"
        run: dotnet restore './libraries/Core/${{ matrix.projects }}'

      - name: ".NET Build: ${{ matrix.projects }}"
        run: dotnet build --configuration Release --no-restore
        working-directory: "./libraries/Core/${{ matrix.projects }}"

      - name: ".NET Unit Tests: ${{ matrix.projects }}"
        if: hashFiles(format('./libraries/Core/{0}/tests/{1}.Tests.csproj', matrix.projects, matrix.projects)) != ''
        run: dotnet test --configuration Release --no-restore
        working-directory: "./libraries/Core/${{ matrix.projects }}/tests"

    # - name: '.NET Benchmarks: ${{ matrix.projects }}'
    #   if: hashFiles(format('./libraries/Core/{0}/benchmarks/{1}.Benchmarks.csproj', matrix.projects, matrix.projects)) != ''
    #   run: dotnet run -c Release --project ./libraries/Core/${{ matrix.projects }}/benchmarks/${{ matrix.projects }}.Benchmarks.csproj --filter "*" --
    #   working-directory: './libraries/Core/${{ matrix.projects }}'
