name: hTTP

on:
  push:
    paths:
      - "**/Directory.Build.props" # When the Global Props File Changes
      - "libraries/Http/**"
      - ".github/workflows/http.yml" # When Pipeline File Changes
  # pull_request:
  #   paths:
  #     - "**/Directory.Build.props" # When the Global Props File Changes
  #     - "libraries/Core/**"
  #     - ".github/workflows/core.yml" # When Pipeline File Changes

jobs:
  build:
    name: "${{ matrix.projects }} [${{ matrix.os }}]"
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: [
            'Assimalign.Cohesion.Http',
            'Assimalign.Cohesion.Http.Transports'
          ]
    steps:
      - uses: actions/checkout@v2
        name: "Checkout: ${{ matrix.projects }}"

      - name: .NET Installation
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            10.x
      - name: ".NET Restore: MSBuild Project"
        run: dotnet restore './build/Tasks'
        
      - name: ".NET Build:  MSBuild Project"
        run: dotnet build --configuration Release --no-restore
        working-directory: "./build/Tasks"

      - name: ".NET Restore: ${{ matrix.projects }}"
        run: dotnet restore './libraries/Http/${{ matrix.projects }}'

      - name: ".NET Build: ${{ matrix.projects }}"
        run: dotnet build --configuration Release --no-restore
        working-directory: "./libraries/Http/${{ matrix.projects }}"

      - name: ".NET Unit Tests: ${{ matrix.projects }}"
        if: hashFiles(format('./libraries/Http/{0}/tests/{1}.Tests.csproj', matrix.projects, matrix.projects)) != ''
        run: dotnet test --configuration Release --no-restore
        working-directory: "./libraries/Http/${{ matrix.projects }}/tests"

    # - name: '.NET Benchmarks: ${{ matrix.projects }}'
    #   if: hashFiles(format('./libraries/Http/{0}/benchmarks/{1}.Benchmarks.csproj', matrix.projects, matrix.projects)) != ''
    #   run: dotnet run -c Release --project ./libraries/Core/${{ matrix.projects }}/benchmarks/${{ matrix.projects }}.Benchmarks.csproj --filter "*" --
    #   working-directory: './libraries/Core/${{ matrix.projects }}'
