name: OpenApi

on:
  push:
    paths: 
      - '**/Directory.Build.props'                        # When the Global Props File Changes
      - 'libraries/OpenApi/**'
      - '.github/workflows/library-openapi.yml'                 # When Pipeline File Changes

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: [
            'Assimalign.Cohesion.OpenApi',
        ]
    steps:
      - uses: actions/checkout@v4
        name: "Checkout: ${{ matrix.projects }}"

      - uses: ./.github/actions/build
        name: "Running Build & Tests: ${{ matrix.projects }}"
        with: 
          area: 'libraries'
          category: 'OpenApi'
          project: ${{ matrix.projects }}
