name: Connections
on:
  push:
    paths:
      - "**/Directory.Build.props" # When the Global Props File Changes
      - "libraries/Connections/**"
      - ".github/actions/build/**" # When Shared Build Action Changes
      - ".github/workflows/library-connections.yml" # When Pipeline File Changes
permissions:
  contents: read
  packages: write

jobs:
  build:
    name: "${{ matrix.projects }} [${{ matrix.os }}]"
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: [
            "Assimalign.Cohesion.Connections",
            "Assimalign.Cohesion.Connections.Tcp",
            "Assimalign.Cohesion.Connections.Udp",
            "Assimalign.Cohesion.Connections.Quic",
            "Assimalign.Cohesion.Connections.Security"
          ]
    steps:
      - uses: actions/checkout@v4
        name: "Checkout: ${{ matrix.projects }}"

      - uses: ./.github/actions/build
        name: "Running Build & Tests: ${{ matrix.projects }}"
        with:
          area: 'libraries'
          category: 'Connections'
          project: ${{ matrix.projects }}
