name: ObjectMapping
on:
  push:
    paths:
      - "libraries/ObjectMapping/**"
      - ".github/workflows/library-object-mapping.yml" # When Pipeline File Changes
permissions:
  contents: read
  packages: write

jobs:
  build:
    name: "${{ matrix.projects }} [${{ matrix.os }}]"
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: [
            'Assimalign.Cohesion.ObjectMapping'
          ]
    steps:
      - uses: actions/checkout@v4
        name: "Checkout: ${{ matrix.projects }}"

      - uses: ./.github/actions/build
        name: "Running Build & Tests: ${{ matrix.projects }}"
        with:
          area: 'libraries'
          category: 'ObjectMapping'
          project: ${{ matrix.projects }}
