name: ObjectValidation
on:
  push:
    paths:
      - "libraries/ObjectValidation/**"
      - ".github/workflows/library-object-validation.yml" # When Pipeline File Changes
permissions:
  contents: read
  packages: write

jobs:
  build:
    name: "${{ matrix.projects }} [${{ matrix.os }}]"
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: [
            "Assimalign.Cohesion.ObjectValidation"
          ]
    steps:
      - uses: actions/checkout@v4
        name: "Checkout: ${{ matrix.projects }}"

      - uses: ./.github/actions/build
        name: "Running Build & Tests: ${{ matrix.projects }}"
        with:
          area: 'libraries'
          category: 'ObjectValidation'
          project: ${{ matrix.projects }}
