name: Content
on:
  push:
    paths:
      - 'libraries/Content/**'
      - '.github/workflows/library-content.yml'                 # When Pipeline File Changes

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: [
            'Assimalign.Cohesion.Content',
            'Assimalign.Cohesion.Content.Text',
            'Assimalign.Cohesion.Content.Ebml',
            'Assimalign.Cohesion.Content.Markdown'
        ]
    steps:
      - uses: actions/checkout@v4
        name: "Checkout: ${{ matrix.projects }}"

      - uses: ./.github/actions/build
        name: "Running Build & Tests: ${{ matrix.projects }}"
        with:
          area: 'libraries'
          category: 'Content'
          project: ${{ matrix.projects }}
