name: Dns
on:
  push:
    paths:
      - "libraries/Dns/**"
      - ".github/workflows/library-dns.yml" # When Pipeline File Changes
permissions:
  contents: read
  packages: write

jobs:
  build:
    name: "${{ matrix.projects }} [${{ matrix.os }}]"
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: [
            "Assimalign.Cohesion.Dns",
            "Assimalign.Cohesion.Dns.Client",
            "Assimalign.Cohesion.Dns.Client.Dot",
            "Assimalign.Cohesion.Dns.Client.Doh",
            "Assimalign.Cohesion.Dns.Client.Doq",
          ]
    steps:
      - uses: actions/checkout@v4
        name: "Checkout: ${{ matrix.projects }}"

      - uses: ./.github/actions/build
        name: "Running Build & Tests: ${{ matrix.projects }}"
        with:
          area: 'libraries'
          category: 'Dns'
          project: ${{ matrix.projects }}
