name: Notification Hub

on:
  push:
    paths: 
      - '**/Directory.Build.props'                        # When the Global Props File Changes
      - 'libraries/NotificationHub/**'
      - '.github/workflows/notification-hub.yml'                 # When Pipeline File Changes

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: [
            'Assimalign.Cohesion.NotificationHub'
        ]
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout: ${{ matrix.projects }}'

    - name: '.NET Restore: ${{ matrix.projects }}'
      run: dotnet restore 
      working-directory: './libraries/NotificationHub/${{ matrix.projects }}'
    
    - name: '.NET Build: ${{ matrix.projects }}'
      run: dotnet build --configuration Release --no-restore
      working-directory:  './libraries/NotificationHub/${{ matrix.projects }}'

    - name: '.NET Unit Tests: ${{ matrix.projects }}'
      run: dotnet test --no-restore --verbosity normal
      working-directory: './libraries/NotificationHub/${{ matrix.projects }}/tests'