name: Web
on:
  push:
    paths: 
      - '**/Directory.Build.props'                        # When the Global Props File Changes
      - 'resources/Web/**'
      - '.github/workflows/resource-web.yml'        # When Pipeline File Changes

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: [
            'Assimalign.Cohesion.Web'
        ]
    steps:
      - uses: actions/checkout@v4
        name: "Checkout: ${{ matrix.projects }}"

      - uses: ./.github/actions/build
        name: "Running Build & Tests: ${{ matrix.projects }}"
        with: 
          area: 'resources'
          category: 'Web'
          project: ${{ matrix.projects }}