name: "Resource - [EventHub]"
on:
  push:
    paths: 
      - '**/Directory.Build.props'                        # When the Global Props File Changes
      - 'resources/EventHub/**'
      - '.github/workflows/resource-event-hub.yml'        # When Pipeline File Changes

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: [
            'Assimalign.Cohesion.EventHub'
        ]
    steps:
      - uses: actions/checkout@v4
        name: "Checkout: ${{ matrix.projects }}"

      - uses: ./.github/actions/build
        name: "Running Build & Tests: ${{ matrix.projects }}"
        with: 
          area: 'resources'
          category: 'EventHub'
          project: ${{ matrix.projects }}