name: Log Space
on:
  push:
    paths:
      - "resources/LogSpace/**"
      - ".github/workflows/resource-log-space.yml" # When Pipeline File Changes

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: ["Assimalign.Cohesion.LogSpace", "Assimalign.Cohesion.LogSpace.ApplicationModel", "Assimalign.Cohesion.LogSpace.Hosting"]
    steps:
      - uses: actions/checkout@v4
        name: "Checkout: ${{ matrix.projects }}"

      - uses: ./.github/actions/build
        name: "Running Build & Tests: ${{ matrix.projects }}"
        with:
          area: "resources"
          category: "LogSpace"
          project: ${{ matrix.projects }}

  sink-sample:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: ['Assimalign.Cohesion.LogSpace.SinkHost']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          global-json-file: global.json
      - run: dotnet build build/Tasks -c Release
      - run: dotnet build resources/LogSpace/samples/${{ matrix.projects }}/${{ matrix.projects }}.csproj -c Release
