name: Database
on:
  push:
    paths:
      - 'resources/Database/**'
      - '.github/workflows/resource-database.yml'        # When Pipeline File Changes

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        projects: [
            'Assimalign.Cohesion.Database'
        ]
    steps:
      - uses: actions/checkout@v4
        name: "Checkout: ${{ matrix.projects }}"

      - uses: ./.github/actions/build
        name: "Running Build & Tests: ${{ matrix.projects }}"
        with:
          area: 'resources'
          category: 'Database'
          project: ${{ matrix.projects }}
