name: Release

on:
  push:
    tags:
      - '0.*'

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x
          8.x
          9.x

    - name: Set Cohesion SDK Version
      id: get_version
      run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV